export const dummyData = {
  Men: [
    {
      id: "m1",
      name: "Sleevless Shirt",
      price: "50.00",
      img: ["/clothes/sleevless-1.avif", "/clothes/sleevless-2.avif"],
      inStock: true,
      description: "Engineered for performance and comfort, the Apollo Running Short is ideal for intense training or casual jogs.",
    },
    {
      id: "m2",
      name: "Classic blue shirt",
      price: "40.00",
      img: ["/clothes/bland-shirt-1.webp","/clothes/bland-shirt-2.webp","/clothes/bland-shirt-3.webp"],
      inStock: true,
      description: "A timeless essential, the Classic White Shirt is perfect for both formal and casual outfits.",
    },
    {
      id: "m3",
      name: "Urban Grey Shirt",
      price: "35.00",
      img: ["/clothes/sand-shirt-1.webp"],
      inStock: false,
      description: "This Urban Grey Shirt delivers a relaxed fit and minimalist style for everyday wear.",
    },
    {
      id: "m4",
      name: "Classic Polo Olive",
      price: "30.00",
      img: ["/clothes/green-polo-1.webp","/clothes/green-pollo-2.webp","/clothes/green-pollo-3.jpg"],
      inStock: true,
      description: "Spacious and sleek, this shoulder bag is designed for daily use with a touch of modern flair.",
    },
    {
      id: "m5",
      name: "Rainproof Backpack",
      price: "35.00",
      img: ["/clothes/rainproof-backpack-1.webp","/clothes/rainproof-backpack-2.webp","/clothes/rainproof-backpack-3.webp"],
      inStock: true,
      description: "A breathable and stylish shirt in a versatile grey tone, perfect for the modern wardrobe.",
    },
    {
      id: "m6",
      name: "Green Straight Pants",
      price: "50.00",
      img: ["/clothes/straight-pants.webp","/clothes/straight-pants-2.webp","/clothes/straight-pants3.webp"],
      inStock: true,
      description: "Lightweight running shorts with moisture-wicking fabric and an ergonomic fit for all-day comfort.",
    },
  ],
  Women: [
    {
      id: "w1",
      name: "Boxy T-Shirt White",
      price: "50.00",
      img: ["/clothes/boxy-shirt-1.webp","/clothes/boxy-shirt-2.webp","/clothes/boxy-shirt-3.webp"],
      inStock: true,
      description: "Stay active in style with these high-performance Apollo Running Shorts tailored for women.",
    },
    {
      id: "w2",
      name: "Anti-odour socks",
      price: "40.00",
      img: ["/clothes/socks-1.webp","/clothes/socks-2.webp"],
      inStock: true,
      description: "Find stunning women’s classics. The white shirt that transitions seamlessly from work to weekend.",
    },
    {
      id: "w3",
      name: "Colorful Dress",
      price: "35.00",
      img: ["/clothes/colorful-shirt-1.jpg","/clothes/colorful-shirt-2.jpg","/clothes/colorful-shirt-3.jpg"],
      inStock: false,
      description: "Soft and stylish grey shirt perfect for layering or wearing solo with your favorite jeans.",
    },
    {
      id: "w4",
      name: "Boxy T-shirt Beige",
      price: "30.00",
      img: ["/clothes/boxy-beige-2.webp","/clothes/boxy-beige-1.webp"],
      inStock: true,
      description: "Add effortless polish to any outfit with this functional yet chic shoulder bag.",
    },
    {
      id: "w5",
      name: "Undershirt Khaki",
      price: "35.00",
      img: ["/clothes/undershirt-khaki-1.webp","/clothes/undershirt-khaki-2.webp"],
      inStock: true,
      description: "A versatile grey shirt that delivers comfort and a confident silhouette for daily wear.",
    },
    {
      id: "w6",
      name: "Apollo Light Top",
      price: "50.00",
      img: ["/clothes/blue-shirt-1.jpg", "/clothes/blue-shirt-2.jpg", "/clothes/blue-shirt-3.jpg"],
      inStock: true,
      description: "Move freely with breathable Apollo shorts — designed for performance, made for comfort.",
    },
  ],
  Kids: [
    {
      id: "k1",
      name: "Boys Dino Top",
      price: "50.00",
      img: ["/clothes/boys-pain-tee-1.webp","/clothes/boys-pain-tee-2.webp"],
      inStock: true,
      description: "Durable and fun — the Apollo Running Short keeps up with every kid's energy.",
    },
    {
      id: "k2",
      name: "Boys Cargo Shorts",
      price: "40.00",
      img: ["/clothes/boy-cargo-short-1.webp","/clothes/boy-cargo-short-2.webp"],
      inStock: true,
      description: "A polished look for school or special occasions — this white shirt is a mini classic.",
    },
    {
      id: "k3",
      name: "Boys Marled Top",
      price: "35.00",
      img: ["/clothes/marled-top.webp"],
      inStock: false,
      description: "Comfy and cool, this grey shirt gives kids a fashionable edge without sacrificing comfort.",
    },
    {
      id: "k4",
      name: "Cropped Baby Tee",
      price: "30.00",
      img: ["/clothes/cropped-baby-tee-1.webp","/clothes/cropped-baby-tee-2.webp"],
      inStock: true,
      description: "Sized just right for kids, this shoulder bag fits essentials for school or day trips.",
    },
    {
      id: "k5",
      name: "Light Shoes",
      price: "35.00",
      img: ["/clothes/basanochkebi-1.webp","/clothes/basanochkebi-2.webp"],
      inStock: true,
      description: "A playful spin on a classic shirt — lightweight, comfy, and ready for anything.",
    },
    {
      id: "k6",
      name: "Jeans Shorts",
      price: "50.00",
      img: ["/clothes/kid-jeans-1.webp","/clothes/kid-jeans-2.webp"],
      inStock: true,
      description: "From gym class to playground, the Apollo shorts are perfect for active little ones.",
    },
  ],
};
