import apolloShort from "../assets/items/apolo.png";
import shirt1 from "../assets/items/shirt.png";
import shirt2 from "../assets/items/shirt2.png";
import bag from "../assets/items/bag.png";

export const dummyData = {
  Men: [
    {
      id: "m1",
      name: "Apollo Running Short",
      price: "50.00",
      img: ["/clothes/sleevless-1.avif", "/clothes/sleevless-2.avif"],
      inStock: true,
      description: "Engineered for performance and comfort, the Apollo Running Short is ideal for intense training or casual jogs.",
    },
    {
      id: "m2",
      name: "Classic White Shirt",
      price: "40.00",
      img: [shirt1],
      inStock: true,
      description: "A timeless essential, the Classic White Shirt is perfect for both formal and casual outfits.",
    },
    {
      id: "m3",
      name: "Urban Grey Shirt",
      price: "35.00",
      img: [shirt2],
      inStock: false,
      description: "This Urban Grey Shirt delivers a relaxed fit and minimalist style for everyday wear.",
    },
    {
      id: "m4",
      name: "Everyday Shoulder Bag",
      price: "30.00",
      img: [bag],
      inStock: true,
      description: "Spacious and sleek, this shoulder bag is designed for daily use with a touch of modern flair.",
    },
    {
      id: "m5",
      name: "Urban Grey Shirt",
      price: "35.00",
      img: [shirt2],
      inStock: true,
      description: "A breathable and stylish shirt in a versatile grey tone, perfect for the modern wardrobe.",
    },
    {
      id: "m6",
      name: "Apollo Running Short",
      price: "50.00",
      img: [apolloShort],
      inStock: true,
      description: "Lightweight running shorts with moisture-wicking fabric and an ergonomic fit for all-day comfort.",
    },
  ],
  Women: [
    {
      id: "w1",
      name: "Apollo Running Short",
      price: "50.00",
      img: [apolloShort],
      inStock: true,
      description: "Stay active in style with these high-performance Apollo Running Shorts tailored for women.",
    },
    {
      id: "w2",
      name: "Classic White Shirt",
      price: "40.00",
      img: [shirt1],
      inStock: true,
      description: "Find stunning women’s classics. The white shirt that transitions seamlessly from work to weekend.",
    },
    {
      id: "w3",
      name: "Urban Grey Shirt",
      price: "35.00",
      img: ["/clothes/colorful-shirt-1.jpg","/clothes/colorful-shirt-2.jpg","/clothes/colorful-shirt-3.jpg"],
      inStock: false,
      description: "Soft and stylish grey shirt perfect for layering or wearing solo with your favorite jeans.",
    },
    {
      id: "w4",
      name: "Everyday Shoulder Bag",
      price: "30.00",
      img: [bag],
      inStock: true,
      description: "Add effortless polish to any outfit with this functional yet chic shoulder bag.",
    },
    {
      id: "w5",
      name: "Urban Grey Shirt",
      price: "35.00",
      img: [shirt2],
      inStock: true,
      description: "A versatile grey shirt that delivers comfort and a confident silhouette for daily wear.",
    },
    {
      id: "w6",
      name: "Apollo Running Short",
      price: "50.00",
      img: ["/clothes/blue-shirt-1.jpg", "/clothes/blue-shirt-2.jpg", "/clothes/blue-shirt-3.jpg"],
      inStock: true,
      description: "Move freely with breathable Apollo shorts — designed for performance, made for comfort.",
    },
  ],
  Kids: [
    {
      id: "k1",
      name: "Apollo Running Short",
      price: "50.00",
      img: [apolloShort],
      inStock: true,
      description: "Durable and fun — the Apollo Running Short keeps up with every kid's energy.",
    },
    {
      id: "k2",
      name: "Classic White Shirt",
      price: "40.00",
      img: [shirt1],
      inStock: true,
      description: "A polished look for school or special occasions — this white shirt is a mini classic.",
    },
    {
      id: "k3",
      name: "Urban Grey Shirt",
      price: "35.00",
      img: [shirt2],
      inStock: false,
      description: "Comfy and cool, this grey shirt gives kids a fashionable edge without sacrificing comfort.",
    },
    {
      id: "k4",
      name: "Everyday Shoulder Bag",
      price: "30.00",
      img: [bag],
      inStock: true,
      description: "Sized just right for kids, this shoulder bag fits essentials for school or day trips.",
    },
    {
      id: "k5",
      name: "Urban Grey Shirt",
      price: "35.00",
      img: [shirt2],
      inStock: true,
      description: "A playful spin on a classic shirt — lightweight, comfy, and ready for anything.",
    },
    {
      id: "k6",
      name: "Apollo Running Short",
      price: "50.00",
      img: [apolloShort],
      inStock: true,
      description: "From gym class to playground, the Apollo shorts are perfect for active little ones.",
    },
  ],
};
